---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment  # Name of the Deployment
  labels:
    app: healthcare
spec:
  replicas: 3  # Number of replicas (pods)
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare-container
        image: nuthan555/myproject2:9  # Replace with your actual image
        ports:
        - containerPort: 8082  # The port your app listens on inside the container
