apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
  labels:
    app: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure
        image: nuthan555/myproject3:7
        ports:
        - containerPort: 8082
