apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure-container
    spec:
      containers:
      - name: medicure
        image: nuthan555/myproject3:12
        ports:
        - containerPort:8082

----
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  selector:
    app: medicure
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8082
  type: NodePort 
